package adatbazisoraclemvc3;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;

public class Nézet extends javax.swing.JFrame {
  private Modell modell = null;
  private DefaultListModel dlm = new DefaultListModel();
  private ArrayList<JCheckBox> cbRészlegLista = new ArrayList<>(); //adatmodell, de csak a felülethez van köze

  /**
   * Creates new form Nézet
   */
  public Nézet(final Modell modell) {
    this.modell=modell;
    this.initComponents(); //ez állítja be a setdefaultcloseoperations-t
    //ide kézzel:
    this.setTitle("Oracle lekérdező 3.0");
    this.setResizable(false);
    this.setLocationRelativeTo(this);
    this.setAlwaysOnTop(true);
    this.pnRészlegek.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    this.részlegListaÉpít();
  }

  private void részlegListaÉpít() {
    ArrayList<String> lista = this.modell.getRészlegLista();
//    System.out.println(lista.size()); //!: olcsó művelet, nem érdemes külön változót neki
    this.pnRészlegek.setLayout(new GridLayout(lista.size(), 1));
    Font betűtípus = new Font("Tahoma", Font.BOLD, 16);
    for (String részlegNév : lista) {
      JCheckBox cb = new JCheckBox(részlegNév);
      cb.setFont(betűtípus);
      this.cbRészlegLista.add(cb); //!: első körben a háttérben intézem el az adatmanipulációt (később rakom ki gui-ra)
      this.pnRészlegek.add(cb);
    }
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    lDolgozók = new javax.swing.JList<>();
    btFizetéstEmel = new javax.swing.JButton();
    pnRészlegek = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel1.setText("Részlegek");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel2.setText("Dolgozók");

    lDolgozók.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    lDolgozók.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(lDolgozók);

    btFizetéstEmel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    btFizetéstEmel.setText("Fizetést emel");
    btFizetéstEmel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btFizetéstEmelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnRészlegekLayout = new javax.swing.GroupLayout(pnRészlegek);
    pnRészlegek.setLayout(pnRészlegekLayout);
    pnRészlegekLayout.setHorizontalGroup(
      pnRészlegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    pnRészlegekLayout.setVerticalGroup(
      pnRészlegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(pnRészlegek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btFizetéstEmel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(pnRészlegek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(btFizetéstEmel))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btFizetéstEmelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFizetéstEmelActionPerformed
    // TODO add your handling code here:
    ArrayList<String> részlegLista = new ArrayList<>();
    for (JCheckBox cb : this.cbRészlegLista) {
      if (cb.isSelected())
//        System.out.println(jCheckBox.getText()+" ");
        részlegLista.add(cb.getText());
    }
//    System.out.println();
    this.dlm.clear();
    if (0 < részlegLista.size()) {
//      if (!this.dlm.isEmpty())
      //Eljárásként (setter) hívjuk meg a függvényt (getter):
      this.modell.dolgozóListaKészít(részlegLista); //!: "protokolláris párbeszéd"; ez egy "setter";
      for (String dolgozóNév : this.modell.getDolgozóLista()) 
        this.dlm.addElement(dolgozóNév);
      this.lDolgozók.setModel(dlm);
    }
  }//GEN-LAST:event_btFizetéstEmelActionPerformed

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(Nézet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(Nézet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(Nézet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(Nézet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new Nézet().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btFizetéstEmel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList<String> lDolgozók;
  private javax.swing.JPanel pnRészlegek;
  // End of variables declaration//GEN-END:variables
}